name: ridewave_driver
description: "RideWave Driver Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  
  # Location & Map
  geolocator: ^10.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  permission_handler: ^11.1.0

  # Local Storage
  shared_preferences: ^2.2.2
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true